### ISSUE TITLE
Broken multipart/form-data array handling

### ISSUE THREAD

**Issue by installgen2** [iron/params#22]
I'm not entirely sure I'm not doing something incorrectly on my end, but it appears as if array handling is working incorrectly.

>```curl http://localhost:3000 -F "array[]=first_value" -F "array[]=the_second_value"```

When running the example file, produces

>```Ok({"array": ["the_second_value"]}```

In the console.

I also get the same result with uploading files, but of course, as shown in the example comments, arrays work normally when handling ```application/x-www-form-urlencoded``` values.

**Comment by SkylerLipthay** [comment]
At first I thought this was simply a shortcoming of `multipart`, but the alternative API it provides that I alluded to in my response to #21 actually simultaneously provides a way to fix this.

The current [`multipart::server::SaveResult`](http://cybergeek94.github.io/multipart/doc/multipart/server/enum.SaveResult.html) interface that `params` uses [here](https://github.com/iron/params/blob/master/src/lib.rs#L590) needs to be replaced with [`multipart::server::Multipart::read_entry`](http://cybergeek94.github.io/multipart/doc/multipart/server/struct.Multipart.html#method.read_entry)/[`foreach_entry`](http://cybergeek94.github.io/multipart/doc/multipart/server/struct.Multipart.html#method.foreach_entry). I think that this implementation switch would take care of both of these issues in one fell swoop.

I'm a bit busy at the moment with some other work. I can get to this in a couple of weeks, or, if this is urgent, I'd be more than happy to help direct you if you want to take a shot at refactoring this.
