### ISSUE TITLE
Re-add File::from

### ISSUE THREAD

**Issue by shssoichiro** [iron/params#28]
In params 0.3, I was using `File::from` for integration tests in another library. In params 0.4, this function has been removed, and I am unable to manually instantiate a `File` because the fields are private.

I would like `File::from` re-added so that I can continue to have mock `File`s in my integration tests.

**Comment by Hoverbear** [comment]
Looks like you're referring to https://github.com/iron/params/blob/e86eb9e46448400765a4f4b62468bfa7eb641a9a/src/conversion.rs#L95-L103 ?

It still exists: https://github.com/iron/params/blob/master/src/conversion.rs#L96-L103

**Comment by shssoichiro** [comment]
No, I'm referring to `From<multipart::server::SavedFile>`, which was removed [here](https://github.com/iron/params/commit/6dfef646429a6b6ec28165c559f6919803f63fd5#diff-b4aea3e418ccdb71239b96952d9cddb6L212).

**Comment by Hoverbear** [comment]
@SkylerLipthay I see you removed this block of code mentioning it wasn't intended to be public. Do you have thoughts on this?

**Comment by SkylerLipthay** [comment]
Hmm, I believe my intention was to hide `multipart` from the public interface entirely, so as to avoid versioning issues. Actually, I think this convoluted interface is a historical remnant of using another form-data library which implemented `Drop` to delete the temporary file, but now we have a different way of doing that...

Anyway, I never considered the need to mock `File`, but it is a reasonable request. Perhaps the right move here is to destructure the `SavedFile` immediately and expose the `File` fields directly? After all, I'm already doing [this silly bit](https://github.com/iron/params/commit/6dfef646429a6b6ec28165c559f6919803f63fd5#diff-b4aea3e418ccdb71239b96952d9cddb6R200). This change would involve making the `File` fields public, so then it would probably be best to remove all of the getters (`path()`, `filename()`, `size()`, `content_type()`). This would be a breaking change, but at first glance I see no other detriments. In fact, this would eliminate the explicit `impl Clone for File` and `impl Debug for File`

@shssoichiro does this sound good? To be clear, the `File` interface would be:

``` rust
pub struct File {
    pub path: PathBuf,
    pub filename: Option<String>,
    pub size: u64,
    pub content_type: Mime,
}
```

**Comment by shssoichiro** [comment]
Yes, that seems reasonable, especially if it results in less code.

**Comment by SkylerLipthay** [comment]
Sounds good. I'm about to fall asleep but I'll fix this and release 0.5 first thing in the morning.

**Comment by Hoverbear** [comment]
You're so awesome!

**Comment by SkylerLipthay** [comment]
0.5.0 published!

@Hoverbear: Thanks for tagging me in this. For some reason I wasn't subscribed to get email notifications for iron/params? Thanks for being so attentive :)

**Comment by Hoverbear** [comment]
@SkylerLipthay Anything I can do to help. :)
