### ISSUE TITLE
build broken

### ISSUE THREAD

**Issue by MarkSwanson** [iron/params#3]
src/conversion.rs:11:5: 11:50 warning: the trait `core::marker::Sized` is not implemented for the type `Self` [E0277]
src/conversion.rs:11     fn from_value(value: &Value) -> Option<Self>;
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/conversion.rs:11:5: 11:50 help: run `rustc --explain E0277` to see a detailed explanation
src/conversion.rs:11:5: 11:50 note: `Self` does not have a constant size known at compile-time
src/conversion.rs:11:5: 11:50 note: this warning results from recent bug fixes and clarifications; it will become a HARD ERROR in the next release. See RFC 1214 for details.
src/conversion.rs:11     fn from_value(value: &Value) -> Option<Self>;
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/conversion.rs:11:5: 11:50 note: required by `core::option::Option`
src/lib.rs:185:19: 185:28 error: cannot move out of type `formdata::UploadedFile`, which defines the `Drop` trait [E0509]
src/lib.rs:185             path: file.path,
                                 ^~~~~~~~~
src/lib.rs:186:23: 186:36 error: cannot move out of type `formdata::UploadedFile`, which defines the `Drop` trait [E0509]
src/lib.rs:186             filename: file.filename,
                                     ^~~~~~~~~~~~~
src/lib.rs:187:27: 187:44 error: cannot move out of type `formdata::UploadedFile`, which defines the `Drop` trait [E0509]
src/lib.rs:187             content_type: file.content_type,
                                         ^~~~~~~~~~~~~~~~~
error: aborting due to 3 previous errors
Could not compile `params`.

**Comment by MarkSwanson** [comment]
More work should be done to get rid of the warnings (which will become HARD errors in the next release) - but this will get you going:

```
diff --git a/src/lib.rs b/src/lib.rs
index fe77e69..51ca9e3 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -182,9 +182,9 @@ impl File {
 impl From<UploadedFile> for File {
     fn from(file: UploadedFile) -> File {
         File {
-            path: file.path,
-            filename: file.filename,
-            content_type: file.content_type,
+            path: file.path.clone(),
+            filename: file.filename.clone(),
+            content_type: file.content_type.clone(),
             size: file.size,
         }
     }
```

**Comment by SkylerLipthay** [comment]
Thanks for this report. Version 0.0.2 should clear all of this up.
