### ISSUE TITLE
Request mutable borrow issue

### ISSUE THREAD

**Issue by mrLSD** [iron/params#30]
I tried use both Params and Router:
```
fn handle_user(req: &mut Request) -> IronResult<Response> {
    use params::{Params, Value};
    use router::Router;
    use iron::status;

    let values = itry!(req.get_ref::<Params>());
    ...
    Ok(Response::with((status::Found, Redirect(url_for!(req, "home_main")))))
}
```

And got error:
```
   |
32 |     let values = itry!(req.get_ref::<Params>());
   |                        --- mutable borrow occurs here
...
38 |         return Ok(Response::with((status::Found, Redirect(url_for!(req, "home_main")))))
   |                                                                    ^^^ immutable borrow occurs here
...
49 | }
   | - mutable borrow ends here
```

It's maybe really simple answer but  I'm confused. Could you help me fix that?

**Comment by SkylerLipthay** [comment]
`Params` is a plugin which extracts from the `Request`'s body, so at some point it requires mutating the `Request`. [`get_ref` returns a reference to the cached extracted parameters `Map` tied to this mutably borrowed `Request`](http://ironframework.io/doc/iron/prelude/trait.Pluggable.html#method.get_ref).

To circumvent this problem, you can either wrap `req.get_ref::<Params>()` in a helper function which extracts the desired parameters specifically...

``` rust
fn extract_myparam(req: &mut Request) -> String {
    use params::FromValue;
    // Panics if the plugin fails, or if "myparam" was not in the request, or if "myparam"
    // could not be converted into a `String` by `FromValue<String>::from_value`:
    String::from_value(req.get_ref::<Params>().unwrap().get("myparam").unwrap()).unwrap()
}
```

Or alternatively you can just use `req.get::<Params>` or `req.compute::<Params>` (see the docs linked above).

Whichever method you choose depends on your use case! In my applications, I typically write a generic `get_param` method that looks something like `fn get_param<T: params::FromValue>(req: &iron::Request, param_path: &[&str]) -> Result<Option<T>, params::ParamsError>` that uses `get_ref` internally like the above example.

I should really document this in the README... you're definitely not the first to have difficulty with this. My apologies! Let me know if you need further clarification.

**Comment by mrLSD** [comment]
Thanks a lot!
I suggest adding examples code to the specific folder with comments for clear understanding.
