### ISSUE TITLE
Unable to parse URL

### ISSUE THREAD

**Issue by MarkSwanson** [iron/params#5]
When POSTing a blob to an Iron server this params library fails to parse the URL.
It looks like the code is trying to parse the body - and it gives this error:

UrlDecodingError(BodyError(BodyError { detail: "Invalid UTF-8 sequence", cause: Utf8Error(Utf8Error { valid_up_to: 1 }) }))

I need more control - I need to be able to explicitly extract params out of the URL - and NOT try any other mechanism.

**Comment by SkylerLipthay** [comment]
Hmm yeah, this is a bit tricky. The core problem is that `params` uses [`urlencoded`'s body parsing](https://github.com/iron/urlencoded/blob/master/src/lib.rs#L98) unconditionally, and so the body of any POST is at least required to be a valid UTF-8 form query string.

My apologies, I hadn't thought of this problem! I'll take a closer look and try to come up with a solution soon.

**Comment by MarkSwanson** [comment]
No worries. 
I found out Iron has the ability to parse URL Query params so I'm using that now.

**Comment by SkylerLipthay** [comment]
You're right, you can use `urlencoded` or `body-parser` directly. I guess `params` will remain an opinionated all-in-one for now. :sweat_smile:

Thanks again!
