### ISSUE TITLE
opsnssl dependencies

### ISSUE THREAD

**Issue by chenbrooks** [iron/params#6]
added dependencies.params in Cargol.toml, and ran a <em>cargo update</em>

> ```
>  Adding openssl-sys v0.7.1
>  Adding openssl-sys v0.6.7
> ```

then ran <em>cargo build</em>, it poped out with 

> native library `openssl` is being linked to by more than one package, and can only be linked to by one package
> 
>  openssl-sys v0.7.1
>  openssl-sys v0.6.7

Would you please help update the related dependencies?

**Comment by SkylerLipthay** [comment]
Hi! Is this still an issue? I believe the openssl dependency is through iron/hyper, which has been updated to use openssl 0.7.
